baseURL = 'https://n-pham.github.io/blog/'
languageCode = 'en-us'
title = 'Nguyen Pham'
theme = 'diary'
copyright = "Disclaimer: posts are my own and do not necessarily reflect the views of my employer"

[params]
favicon = 'images/favicon.ico'
subtitle = "Multi-Cloud | Big Data & Analytics Lead"

[markup]
  [markup.highlight]
    style = "onedark"
    lineNos = false

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Timeline"
weight = 1

[[menu.main]]
url = "https://www.linkedin.com/in/nguyen-pham-db/"
name = "LinkedIn"
weight = 3