baseURL = 'https://n-pham.github.io/blog/'
languageCode = 'en-us'
title = 'Nguyen Pham'
theme = 'diary'

[markup]
  [markup.highlight]
    style = "onedark"
    lineNos = false

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Timeline"
weight = 1